config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  resources :posts, only: [] do
    collection do
      get 'simple_cached_index'
      get 'time_based_cache_index'
      get 'update_time_based_cache_index'
    end
  end

  root 'home#all'

  resources :topics, only: [:index, :show]

  get 'api/products_and_posts_by_date', format: 'json'
  get 'api/products_and_posts_conditional', format: 'json'
  get 'api/products', fromat: 'json'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
end

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/concerns/display_on_main_page.rb
module DisplayOnMainPage
  extend ActiveSupport::Concern

  MAIN_PAGE_CACHE_KEY = 'current_main_page_cache_key'
  included do
    after_save :change_cache_key
    after_destroy :change_cache_key
  end

  def change_cache_key
    Rails.logger.info 'Expiring Cache for main page by changing cache key'
    Rails.cache.write(MAIN_PAGE_CACHE_KEY, SecureRandom.base64)
  end

  def self.current_cache_key
    Rails.cache.fetch(MAIN_PAGE_CACHE_KEY) { SecureRandom.base64 }
  end
end

app/models/concerns/topicable.rb
module Topicable
  extend ActiveSupport::Concern

  included do
    # touch updates topic allowing for russian doll caching
    belongs_to :topic, touch: true
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include DisplayOnMainPage
  include Topicable
  
  has_many :comments
  belongs_to :user
  scope :visible, -> { where(visible: true) }
end

# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  content    :text
#  visible    :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  topic_id   :integer
#

app/models/product.rb
class Product < ActiveRecord::Base
  include DisplayOnMainPage
  include Topicable
  
  scope :for_sale, -> { where(sellable: true) }
end

# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  sellable    :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  topic_id    :integer
#

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
end

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  biography  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/api_controller.rb
class ApiController < ApplicationController
  layout false

  def products
    cache_key = "products/#{Product.maximum(:updated_at)}"
    products = Rails.cache.fetch(cache_key) do
      Rails.logger.info 'querying for products and building json'
      Product.for_sale.to_json
    end

    render json: products
  end

  def products_and_posts_by_date
    render json: products_and_posts
  end

  def products_and_posts_conditional
    etag = DisplayOnMainPage.current_cache_key
    if stale?(etag)
      Rails.logger.info 'Rendering products and posts'
      render json: products_and_posts
    end
  end

  protected

  def products_and_posts
    Rails.cache.fetch(DisplayOnMainPage.current_cache_key) do
      Rails.logger.info 'querying for new products and posts'
      posts = Post.visible.includes(:user)
      products = Product.for_sale
      (products + posts).sort_by(&:created_at).reverse.to_json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  # This is naive implementation
  def simple_cached_index
    @posts =  posts_query
  end

  # This is also a naive implementation
  def time_based_cache_index
    @posts = posts_query
  end

  # NOTE:  Table should be insert/update only (No deletes!)
  def update_time_based_cache_index
    @cache_key = "posts/#{Post.maximum(:updated_at)}"
    @posts = posts_query
  end

  protected

  def posts_query
    Post.visible.includes(:user)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @cache_key = "topic_index/#{Topic.maximum(:updated_at)}"
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def posts_cache_key
    "posts/#{Post.maximum(:updated_at)}"
  end

  def products_cache_key
    "products/#{Product.maximum(:updated_at)}"
  end
end

app/views/home/all.haml
%h2  Products and Posts

= react_component('AllListings')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CachingExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_summary.haml
%header
  %h4= post.title
  .byline By #{post.user.name}
  .time #{post.updated_at.strftime('%A %B, %e %I:%M %p')}
%p= post.content.truncate(200)

app/views/posts/_summary_with_index.haml
- cache post do
  = render partial: 'posts/summary', locals: { post: post }
  %h5 Comments: #{post.comments.count}
  

app/views/posts/simple_cached_index.haml
- cache do
  %h2 Posts Index

  = render partial: 'summary', collection: @posts, as: :post

app/views/posts/time_based_cache_index.haml
- cache 'time-based-posts-index', expires_in: 10.minutes do
  %h2 Posts Index

  = render partial: 'summary', collection: @posts, as: :post

app/views/posts/update_time_based_cache_index.haml
-# cached by last updated at time
- cache @cache_key do
  %h2 Posts Index

  = render partial: 'summary', collection: @posts, as: :post

app/views/products/_product.haml
- cache product do
  %h4= product.name
  %h5 Yours for only #{number_to_currency(product.price)}
  %p= product.description

app/views/topics/index.haml
- cache @cache_key do
  %h1 All Topics

  - @topics.each do |topic|
    - cache topic do
      %h2
        = link_to topic.name, topic_path(topic)
      Products: #{topic.products.for_sale.count} | Posts: #{topic.posts.visible.count}

      %h5 Most recent post:
      = render partial: 'posts/summary', locals: { post: topic.posts.visible.order(created_at: :desc).first }

app/views/topics/show.haml
- cache @topic do
  %h1= @topic.name

  - cache posts_cache_key do
    %h2 Posts
    = render partial: 'posts/summary_with_index', collection: @topic.posts.visible, as: :post

  - cache products_cache_key do
    %h2 Related Products to Purchase
    = render partial: 'products/product', collection: @topic.products.for_sale, as: :product